package com.example.lab.UI;

import com.example.lab.Controller.BasicEquipmentController;
import com.example.lab.Entity.BorrowReturn;
import com.example.lab.Util.ApplicationContextUtil;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Locale;

public class borrow_equipment {
    static JFrame frame = new JFrame("实验室设备管理系统");
    private JPanel root;
    private BackgroundPanel panel1;
    private JTextField eq_name;
    private JTextField user_id;
    private JButton exit;
    private JButton yes;
    private JTextField num;


    public borrow_equipment() {
        exit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                closepage();
                new borrow_return_equipment().init();
            }
        });
        yes.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (num.getText().equals("")) {
                    /******错误弹窗调用***********/
                    JOptionPane.showMessageDialog(null, "填入数据不可为空");
                } else {
                    String userID = user_id.getText();
                    String equipment_name = eq_name.getText();
                    int number = Integer.parseInt(num.getText());
                    BorrowReturn br=new BorrowReturn();
                    br.setBorrower(userID);
                    br.setEquipmentName(equipment_name);
                    br.setNumber(number);
                    BasicEquipmentController controller = (BasicEquipmentController) ApplicationContextUtil.getBean("BasicEquipmentController");
                    String info =controller.insertBorrow(br, Token.token).info;
                    JOptionPane.showMessageDialog(null, info);
                    if(info.equals("借用成功")){
                        closepage();
                        new borrow_return_equipment().init();
                        return;
                    }
                }
            }
        });
    }

    public void init() {
        frame.setContentPane(new borrow_equipment().root);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setBounds(600, 300, 800, 400);
        frame.pack();
        frame.setVisible(true);
    }

    public void closepage() {
        frame.dispose();

    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        root = new JPanel();
        root.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1 = new BackgroundPanel();
        panel1.setImagestr("src/main/resources/picture/AA.png");
        panel1.setLayout(new FormLayout("fill:max(d;4px):noGrow,left:68dlu:noGrow,left:50dlu:noGrow,left:103dlu:noGrow,fill:93px:noGrow,left:69dlu:noGrow,fill:max(d;4px):noGrow", "center:61px:noGrow,top:20dlu:noGrow,center:28dlu:noGrow,center:28dlu:noGrow,top:28dlu:noGrow,center:max(d;4px):noGrow,top:35dlu:noGrow,center:29px:noGrow"));
        panel1.setBackground(new Color(-4272661));
        panel1.setForeground(new Color(-5922902));
        root.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setForeground(new Color(-4928789));
        CellConstraints cc = new CellConstraints();
        panel1.add(label1, cc.xy(2, 1));
        final JLabel label2 = new JLabel();
        Font label2Font = this.$$$getFont$$$(null, Font.BOLD, 26, label2.getFont());
        if (label2Font != null) label2.setFont(label2Font);
        label2.setForeground(new Color(-3771247));
        label2.setText("借用设备");
        panel1.add(label2, cc.xyw(3, 1, 3, CellConstraints.CENTER, CellConstraints.DEFAULT));
        final JLabel label3 = new JLabel();
        Font label3Font = this.$$$getFont$$$(null, Font.BOLD, 20, label3.getFont());
        if (label3Font != null) label3.setFont(label3Font);
        label3.setForeground(new Color(-0));
        label3.setText("设备名称");
        panel1.add(label3, cc.xy(3, 4, CellConstraints.CENTER, CellConstraints.CENTER));
        eq_name = new JTextField();
        panel1.add(eq_name, cc.xy(4, 4, CellConstraints.FILL, CellConstraints.CENTER));
        user_id = new JTextField();
        panel1.add(user_id, cc.xy(4, 3, CellConstraints.FILL, CellConstraints.CENTER));
        final JLabel label4 = new JLabel();
        Font label4Font = this.$$$getFont$$$(null, Font.BOLD, 20, label4.getFont());
        if (label4Font != null) label4.setFont(label4Font);
        label4.setForeground(new Color(-0));
        label4.setText("借用人ID");
        panel1.add(label4, cc.xy(3, 3, CellConstraints.CENTER, CellConstraints.CENTER));
        final JLabel label5 = new JLabel();
        Font label5Font = this.$$$getFont$$$(null, Font.BOLD, 20, label5.getFont());
        if (label5Font != null) label5.setFont(label5Font);
        label5.setForeground(new Color(-0));
        label5.setText("借用数量");
        panel1.add(label5, cc.xy(3, 5, CellConstraints.CENTER, CellConstraints.CENTER));
        num = new JTextField();
        num.setText("");
        panel1.add(num, cc.xy(4, 5, CellConstraints.FILL, CellConstraints.CENTER));
        yes = new JButton();
        yes.setText("确定");
        panel1.add(yes, cc.xy(3, 7, CellConstraints.RIGHT, CellConstraints.CENTER));
        exit = new JButton();
        exit.setText("返回");
        yes.setBackground(new Color(230,230,250));
        exit.setBackground(new Color(230,230,250));
        panel1.add(exit, cc.xy(5, 7, CellConstraints.LEFT, CellConstraints.CENTER));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return root;
    }

}
