package com.example.lab.UI;
import com.example.lab.Controller.BasicEquipmentController;
import com.example.lab.Entity.BorrowReturn;
import com.example.lab.Util.ApplicationContextUtil;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Locale;

public class userBorrowUpdate {
    static JFrame frame = new JFrame("userBorrowUpdate");
    private JTextField eq_name;
    private JTextField num;
    private JButton exit;
    private JPanel root;
    private JPanel panel1;
    private JTextField eq_id;
    private JTextField borrow_id;
    private JButton sure;

    public userBorrowUpdate() {
        exit.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                closepage();
                new user_br_eq().init();
            }
        });
        sure.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (borrow_id.getText().equals("") || num.getText().equals("") || eq_id.getText().equals("")) {
                    /******错误弹窗调用***********/
                    JOptionPane.showMessageDialog(null, "填入数据不可为空");
                } else {
                    int borrowid = Integer.parseInt(borrow_id.getText());
                    int eqid = Integer.parseInt(eq_id.getText());
                    String equipment_name = eq_name.getText();
                    int number = Integer.parseInt(num.getText());
                    BorrowReturn borrowReturn=new BorrowReturn();
                    borrowReturn.setBorrowId(borrowid);
                    borrowReturn.setEquipmentId(eqid);
                    borrowReturn.setEquipmentName(equipment_name);
                    borrowReturn.setNumber(number);

                    BasicEquipmentController controller = (BasicEquipmentController) ApplicationContextUtil.getBean("BasicEquipmentController");
                    String info =controller.update(borrowReturn, Token.token).info;
                    JOptionPane.showMessageDialog(null, info);
                    if (info.equals("更新成功")){
                        closepage();
                        new user_br_eq().init();
                        return;
                    }
                }
            }
        });
    }

    public void init() {
        frame.setContentPane(new userBorrowUpdate().root);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    public void closepage() {
        frame.dispose();
    }

    public static void main(String[] args) {
        new userBorrowUpdate().init();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        root = new JPanel();
        root.setLayout(new FormLayout("fill:d:grow", "center:d:grow"));
        panel1 = new JPanel();
        panel1.setLayout(new FormLayout("left:68dlu:noGrow,left:50dlu:noGrow,left:103dlu:noGrow,fill:93px:noGrow,left:69dlu:noGrow,fill:max(d;4px):noGrow", "center:61px:noGrow,top:13dlu:noGrow,top:28dlu:noGrow,center:28dlu:noGrow,center:28dlu:noGrow,top:28dlu:noGrow,center:61px:noGrow,top:31dlu:noGrow,center:max(d;4px):noGrow"));
        panel1.setBackground(new Color(-4272661));
        panel1.setForeground(new Color(-5922902));
        CellConstraints cc = new CellConstraints();
        root.add(panel1, cc.xy(1, 1, CellConstraints.DEFAULT, CellConstraints.FILL));
        final JLabel label1 = new JLabel();
        label1.setForeground(new Color(-4928789));
        label1.setText("Label");
        panel1.add(label1, cc.xy(1, 1));
        final JLabel label2 = new JLabel();
        Font label2Font = this.$$$getFont$$$(null, Font.BOLD, 26, label2.getFont());
        if (label2Font != null) label2.setFont(label2Font);
        label2.setForeground(new Color(-3771247));
        label2.setText("更新借用设备信息");
        panel1.add(label2, cc.xyw(2, 1, 3, CellConstraints.CENTER, CellConstraints.DEFAULT));
        final JLabel label3 = new JLabel();
        Font label3Font = this.$$$getFont$$$(null, Font.PLAIN, 20, label3.getFont());
        if (label3Font != null) label3.setFont(label3Font);
        label3.setForeground(new Color(-5409849));
        label3.setText("借还表id");
        panel1.add(label3, cc.xy(2, 3, CellConstraints.CENTER, CellConstraints.CENTER));
        final JLabel label4 = new JLabel();
        Font label4Font = this.$$$getFont$$$(null, Font.PLAIN, 20, label4.getFont());
        if (label4Font != null) label4.setFont(label4Font);
        label4.setForeground(new Color(-5409849));
        label4.setText("设备id");
        panel1.add(label4, cc.xy(2, 4, CellConstraints.CENTER, CellConstraints.CENTER));
        eq_id = new JTextField();
        panel1.add(eq_id, cc.xy(3, 4, CellConstraints.FILL, CellConstraints.CENTER));
        borrow_id = new JTextField();
        panel1.add(borrow_id, cc.xy(3, 3, CellConstraints.FILL, CellConstraints.CENTER));
        final JLabel label5 = new JLabel();
        Font label5Font = this.$$$getFont$$$(null, Font.PLAIN, 20, label5.getFont());
        if (label5Font != null) label5.setFont(label5Font);
        label5.setForeground(new Color(-5409849));
        label5.setText("设备名字");
        panel1.add(label5, cc.xy(2, 5, CellConstraints.CENTER, CellConstraints.CENTER));
        eq_name = new JTextField();
        eq_name.setText("");
        panel1.add(eq_name, cc.xy(3, 5, CellConstraints.FILL, CellConstraints.CENTER));
        final JLabel label6 = new JLabel();
        Font label6Font = this.$$$getFont$$$(null, Font.PLAIN, 20, label6.getFont());
        if (label6Font != null) label6.setFont(label6Font);
        label6.setForeground(new Color(-5409849));
        label6.setText("数量");
        panel1.add(label6, cc.xy(2, 6, CellConstraints.CENTER, CellConstraints.CENTER));
        num = new JTextField();
        num.setText("");
        panel1.add(num, cc.xy(3, 6, CellConstraints.FILL, CellConstraints.CENTER));
        sure = new JButton();
        sure.setText("确定");
        panel1.add(sure, cc.xy(2, 7, CellConstraints.RIGHT, CellConstraints.DEFAULT));
        exit = new JButton();
        exit.setText("返回");
        panel1.add(exit, cc.xy(4, 7, CellConstraints.LEFT, CellConstraints.DEFAULT));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return root;
    }

}
